// src/utils/receiptGenerator.ts
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system";
import { Alert, Platform } from "react-native";
import { Asset } from "expo-asset";

/* ─────────────────────────────────────────────────────────────────────────────
   TYPES
───────────────────────────────────────────────────────────────────────────── */

export interface PaymentReceiptData {
  /** Receipt date (defaults to current date if not provided) */
  date?: Date | string;
  /** Tenant/Customer name */
  tenantName: string;
  /** Room number or unit */
  roomNumber: string;
  /** Mobile/Phone number */
  mobileNumber: string;
  /** Sharing type (for PG/hostel) */
  sharingType?: number | string;
  /** Payment details - list of items with description and amount */
  paymentItems: Array<{
    description: string;
    amount: number;
  }>;
  /** Grand total amount */
  grandTotal: number;
  /** Payment mode (cash, UPI, card, etc.) */
  paymentMode: string;
  /** Property/Business name */
  propertyName?: string;
  /** Custom footer message */
  footerMessage?: string;
}

export interface ReceiptGeneratorOptions {
  /** File name for the PDF (without extension) */
  fileName?: string;
  /** Whether to share after generating (default: true) */
  shareAfterGenerate?: boolean;
  /** Custom logo base64 (if not using default) */
  customLogoBase64?: string;
}

/* ─────────────────────────────────────────────────────────────────────────────
   LOGO BASE64 (Embedded PGMS Logo)
───────────────────────────────────────────────────────────────────────────── */

// This will be loaded dynamically from the asset
let cachedLogoBase64: string | null = null;

/**
 * Load the logo image and convert to base64
 */
const loadLogoBase64 = async (): Promise<string> => {
  if (cachedLogoBase64) {
    return cachedLogoBase64;
  }

  try {
    // Load the logo asset
    const logoAsset = Asset.fromModule(require("@/assets/images/logo.png"));
    await logoAsset.downloadAsync();

    if (logoAsset.localUri) {
      const base64 = await FileSystem.readAsStringAsync(logoAsset.localUri, {
        encoding: FileSystem.EncodingType.Base64,
      });
      cachedLogoBase64 = `data:image/png;base64,${base64}`;
      return cachedLogoBase64;
    }
  } catch (error) {
    // Fallback: Return empty string if logo loading fails
  }

  return "";
};

/* ─────────────────────────────────────────────────────────────────────────────
   HELPERS
───────────────────────────────────────────────────────────────────────────── */

/**
 * Format date to DD/MM/YYYY
 */
const formatDate = (date?: Date | string): string => {
  const d = date ? new Date(date) : new Date();
  if (isNaN(d.getTime())) return new Date().toLocaleDateString("en-GB");

  const day = String(d.getDate()).padStart(2, "0");
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const year = d.getFullYear();
  return `${day}/${month}/${year}`;
};

/**
 * Format currency in INR
 */
const formatCurrency = (amount: number): string => {
  return amount.toLocaleString("en-IN");
};

/**
 * Capitalize first letter
 */
const capitalize = (str: string): string => {
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
};

/**
 * Get month name from date
 */
const getMonthName = (date?: Date | string): string => {
  const d = date ? new Date(date) : new Date();
  if (isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-US", { month: "short" });
};

/* ─────────────────────────────────────────────────────────────────────────────
   HTML TEMPLATE
───────────────────────────────────────────────────────────────────────────── */

/**
 * Generate HTML template for the receipt - matching web version exactly
 */
const generateReceiptHTML = (
  data: PaymentReceiptData,
  logoBase64: string
): string => {
  const {
    date,
    tenantName,
    roomNumber,
    mobileNumber,
    sharingType,
    paymentItems,
    grandTotal,
    paymentMode,
    propertyName = "PGMS",
    footerMessage,
  } = data;

  const formattedDate = formatDate(date);
  const formattedTotal = grandTotal;

  // Generate payment items rows (simple format like web version)
  const paymentItemsHTML = paymentItems
    .map(
      (item) => `
        <tr>
          <td>${item.description}</td>
          <td class="amount">${item.amount}</td>
        </tr>
      `
    )
    .join("");

  // Auto-generated message
  const autoGeneratedMessage =
    footerMessage ||
    `This invoice is automatically generated by ${propertyName.toLowerCase()} via PGMS and does not require a physical signature.`;

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Payment Receipt</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #FFFFFF;
      color: #333333;
      line-height: 1.6;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 3px solid #6C3FC0;
    }
    
    .logo-section {
      display: flex;
      align-items: center;
    }
    
    .logo {
      height: 60px;
      width: auto;
    }
    
    .date-section {
      text-align: right;
      font-size: 14px;
      color: #555;
    }
    
    .date-section strong {
      color: #333;
    }
    
    /* Tenant Details Table - matching web version */
    .tenant-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 30px;
      border: 1px solid #ddd;
    }
    
    .tenant-table td {
      padding: 12px 15px;
      border: 1px solid #ddd;
      font-size: 14px;
    }
    
    .tenant-table td strong {
      color: #6C3FC0;
    }
    
    /* Payment Details Section */
    .section-title {
      font-size: 20px;
      font-weight: bold;
      color: #333;
      margin: 25px 0 15px 0;
      padding-bottom: 10px;
      border-bottom: 2px solid #6C3FC0;
    }
    
    .payment-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    
    .payment-table td {
      padding: 10px 0;
      font-size: 14px;
      border-bottom: 1px solid #eee;
    }
    
    .payment-table td.amount {
      text-align: right;
      font-weight: 600;
    }
    
    /* Grand Total Section */
    .grand-total {
      background: linear-gradient(135deg, #6C3FC0 0%, #8B5CF6 100%);
      color: white;
      padding: 15px 20px;
      margin: 20px 0;
      border-radius: 8px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    
    .grand-total-label {
      font-size: 18px;
      font-weight: bold;
      text-transform: uppercase;
    }
    
    .grand-total-amount {
      font-size: 24px;
      font-weight: bold;
    }
    
    /* Payment Mode */
    .payment-mode {
      font-size: 14px;
      color: #555;
      margin: 15px 0;
      padding: 10px 15px;
      background: #f8f9fa;
      border-radius: 5px;
      border-left: 4px solid #28a745;
    }
    
    .payment-mode strong {
      color: #333;
    }
    
    /* Auto Generated Notice */
    .auto-notice {
      font-size: 12px;
      color: #666;
      font-style: italic;
      margin: 20px 0;
      padding: 15px;
      background: #fff8e6;
      border-radius: 5px;
      border-left: 4px solid #ffc107;
      line-height: 1.5;
    }
    
    /* Terms Section */
    .terms-section {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
    }
    
    .terms-title {
      font-size: 16px;
      font-weight: bold;
      color: #333;
      margin-bottom: 10px;
    }
    
    .terms-content {
      font-size: 11px;
      color: #666;
      line-height: 1.6;
      text-align: justify;
    }
    
    /* Divider */
    hr {
      border: none;
      border-top: 1px solid #ddd;
      margin: 20px 0;
    }
    
    @media print {
      body {
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <!-- Header with Logo and Date -->
  <div class="header">
    <div class="logo-section">
      ${logoBase64 ? `<img src="${logoBase64}" alt="PGMS Logo" class="logo" />` : '<span style="font-size: 28px; font-weight: bold; color: #6C3FC0;">PGMS</span>'}
    </div>
    <div class="date-section">
      <strong>Date :</strong> ${formattedDate}
    </div>
  </div>
  
  <!-- Tenant Details Table -->
  <table class="tenant-table">
    <tr>
      <td><strong>Tenant Name :</strong> ${tenantName}</td>
      <td><strong>Room Number :</strong> ${roomNumber}</td>
    </tr>
    <tr>
      <td><strong>Mobile Number :</strong> ${mobileNumber}</td>
      ${sharingType ? `<td><strong>Sharing Type :</strong> ${sharingType}</td>` : "<td></td>"}
    </tr>
  </table>
  
  <!-- Payment Details -->
  <h2 class="section-title">Payment Details</h2>
  <table class="payment-table">
    ${paymentItemsHTML}
  </table>
  
  <!-- Grand Total -->
  <div class="grand-total">
    <span class="grand-total-label">GRAND TOTAL</span>
    <span class="grand-total-amount">${formattedTotal}</span>
  </div>
  
  <!-- Payment Mode -->
  <div class="payment-mode">
    <strong>Payment Mode :</strong> ${capitalize(paymentMode)}
  </div>
  
  <!-- Auto Generated Notice -->
  <div class="auto-notice">
    ${autoGeneratedMessage}
  </div>
  
  <hr />
  
  <!-- Terms & Conditions -->
  <div class="terms-section">
    <h3 class="terms-title">Terms & Conditions</h3>
    <p class="terms-content">
      This receipt acknowledges the payment made by the tenant through any available payment method for the provided services. In case of failed or incomplete payments, for any reason, this receipt will become null and void. No claims for refunds or discounts will be entertained based on this receipt under any circumstances.
    </p>
  </div>
</body>
</html>
  `;
};

/* ─────────────────────────────────────────────────────────────────────────────
   MAIN EXPORT FUNCTIONS
───────────────────────────────────────────────────────────────────────────── */

/**
 * Generate and share/download a payment receipt PDF
 */
export const generatePaymentReceipt = async (
  data: PaymentReceiptData,
  options: ReceiptGeneratorOptions = {}
): Promise<{ success: boolean; filePath?: string; error?: string }> => {
  const {
    fileName = `Payment_Receipt_${Date.now()}`,
    shareAfterGenerate = true,
    customLogoBase64,
  } = options;

  try {
    // Load logo
    const logoBase64 = customLogoBase64 || (await loadLogoBase64());

    // Generate HTML
    const html = generateReceiptHTML(data, logoBase64);

    // Generate PDF
    const { uri } = await Print.printToFileAsync({
      html,
      base64: false,
    });

    // Rename file if on supported platform
    let finalUri = uri;
    if (Platform.OS !== "web") {
      const pdfName = `${fileName}.pdf`;
      const directory = FileSystem.documentDirectory;
      if (directory) {
        finalUri = `${directory}${pdfName}`;
        await FileSystem.moveAsync({
          from: uri,
          to: finalUri,
        });
      }
    }

    // Share the PDF
    if (shareAfterGenerate) {
      const isAvailable = await Sharing.isAvailableAsync();
      if (isAvailable) {
        await Sharing.shareAsync(finalUri, {
          mimeType: "application/pdf",
          dialogTitle: "Save or Share Receipt",
          UTI: "com.adobe.pdf",
        });
      } else {
        Alert.alert(
          "Sharing Unavailable",
          "Sharing is not available on this device. The receipt has been saved.",
          [{ text: "OK" }]
        );
      }
    }

    return { success: true, filePath: finalUri };
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Failed to generate receipt";
    return { success: false, error: errorMessage };
  }
};

/**
 * Generate receipt data from a collection payment object
 * This is a convenience function to transform API data to receipt format
 */
export const createReceiptDataFromCollection = (
  collection: {
    tenantDetails?: {
      name?: string;
      roomNumber?: string;
      phoneNumber?: string;
      sharingType?: number;
    };
    paymentDate?: string;
    dueDate?: string;
    paymentCategory?: string;
    amount?: number;
    totalAmount?: number;
    paymentMode?: string;
  },
  propertyName?: string
): PaymentReceiptData => {
  const tenantName = collection.tenantDetails?.name || "N/A";
  const roomNumber = collection.tenantDetails?.roomNumber || "N/A";
  const mobileNumber = collection.tenantDetails?.phoneNumber || "N/A";
  const sharingType = collection.tenantDetails?.sharingType;
  const paymentDate = collection.paymentDate;
  const dueDate = collection.dueDate;
  const category = collection.paymentCategory || "Payment";
  const amount = collection.amount || 0;
  const paymentMode = collection.paymentMode || "Cash";

  // Get month name from due date for the description
  const monthName = dueDate ? getMonthName(dueDate) : "";
  const description = monthName
    ? `${monthName} ${capitalize(category)}`
    : capitalize(category);

  return {
    date: paymentDate,
    tenantName,
    roomNumber,
    mobileNumber,
    sharingType,
    paymentItems: [
      {
        description,
        amount,
      },
    ],
    grandTotal: amount,
    paymentMode,
    propertyName,
  };
};

/**
 * Preview receipt in print dialog (useful for debugging or direct printing)
 */
export const previewReceipt = async (
  data: PaymentReceiptData
): Promise<void> => {
  try {
    const logoBase64 = await loadLogoBase64();
    const html = generateReceiptHTML(data, logoBase64);
    await Print.printAsync({ html });
  } catch (error) {
    Alert.alert("Error", "Failed to preview receipt. Please try again.");
  }
};

export default {
  generatePaymentReceipt,
  createReceiptDataFromCollection,
  previewReceipt,
};

